version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql_network

  adminer:
    image: adminer:latest
    container_name: adminer_container
    ports:
      - "8181:8080"
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
